apiVersion: apps/v1
kind: Deployment
metadata:
  name: "3030-deployment"
spec:
  selector:
    matchLabels:
      app: "3030"
  replicas: 2
  template:
    metadata:
      labels:
        app: "3030"
    spec:
      containers:
      - image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
        name: "3030"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "service-3030"
spec:
  ports:
    - port: 80
      targetPort: 81
      protocol: TCP
  type: NodePort
  selector:
    app: "3030"